### ISSUE TITLE
FreeBSD系统下报错

### ISSUE THREAD

**Issue by Komorebi-yaodong** [synodriver/pysilk#4]
报错如下：
```
Traceback (most recent call last):
  File "/usr/home/***/tmp/test.py", line 1, in <module>
    import pysilk
  File "/home/***/.local/lib/python3.11/site-packages/pysilk/__init__.py", line 18, in <module>
    from pysilk.backends.cython import *
  File "/home/***/.local/lib/python3.11/site-packages/pysilk/backends/cython/__init__.py", line 4, in <module>
    from pysilk.backends.cython._silk import *
ModuleNotFoundError: No module named 'pysilk.backends.cython._silk'
```
本地编译也成功了，但是依旧报错

**Comment by synodriver** [comment]
是没有那个C模块吗？应该有个类似_silk.so的东西

**Comment by synodriver** [comment]
注意编译指令是python setup.py bdist_wheel --use-cython --use-cffi
